FIXING - AttributeError: 'WebDriver' object has no attribute 'find_element_by_id'
Updated find_element_by_id to find_element since find_element_by_id is no longer available